[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mkdocs-void"
version = "0.2.1"
description = "Void is a new design language for MkDocs themes: a drop-in theme (name: void) and companion plugin on top of MkDocs."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ["mkdocs", "theme", "documentation", "rkriad585", "neostore", "glass", "glassmorphism", "nothingos", "void", "mkdocs-theme", "pwa", "static-site", "design-system", "fast", "web"]
authors = [
  { name = "rkriad585", email = "rkriad585@gmail.com" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Framework :: MkDocs",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: JavaScript",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Documentation",
  "Topic :: Internet :: WWW/HTTP :: Site Management",
  "Topic :: Software Development :: Documentation",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Text Processing :: Markup :: HTML",
]
dependencies = ["mkdocs>=1.5", "pymdown-extensions>=10.0", "Pygments>=2.18"]

[project.optional-dependencies]
social-cards = ["Pillow>=9.0"]
docs = ["mkdocs-section-index>=0.3.5", "mkdocs-glightbox>=0.4.0", "Pillow>=9.0"]
dev = ["build>=1.0", "ruff>=0.5"]

[project.urls]
Homepage = "https://github.com/rkriad585/mkdocs-void"
Documentation = "https://rkriad585.github.io/mkdocs-void"
Source = "https://github.com/rkriad585/mkdocs-void"
Issues = "https://github.com/rkriad585/mkdocs-void/issues"
Changelog = "https://github.com/rkriad585/mkdocs-void/blob/main/CHANGELOG.md"
Funding = "https://github.com/sponsors/rkriad585"
"Open Collective" = "https://opencollective.com/rkriad585"
Tidelift = "https://tidelift.com/funding/github/pypi/mkdocs-void"
Patreon = "https://www.patreon.com/rkriad585"

[project.entry-points."mkdocs.themes"]
void = "void.templates"

[project.entry-points."mkdocs.plugins"]
void = "void.plugins.void_plugin:VoidPlugin"

[project.scripts]
void = "void.cli:main"

[tool.hatch.build.targets.wheel]
include = ["/void"]
exclude = ["void/templates/assets/stylesheets/*.scss"]

[tool.hatch.build.targets.sdist]
include = ["/void", "/package.json", "/requirements.txt"]
